DO $$ BEGIN
  CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

ALTER TABLE "Student"
ADD COLUMN IF NOT EXISTS "gender" "Gender" NOT NULL DEFAULT 'MALE';
