@echo off
REM MediaMTX Restart Script - Config yangilanganda ishlatiladi
echo Restarting MediaMTX...
taskkill /IM mediamtx.exe /F 2>nul
timeout /t 1 /nobreak >nul
cd /d "%~dp0"
REM Prefer autogen config if present (generated by the backend on startup)
if exist "mediamtx.autogen.yml" (
  start "" /min mediamtx.exe mediamtx.autogen.yml
) else (
  start "" /min mediamtx.exe mediamtx.yml
)
echo MediaMTX restarted successfully!
