import type React from 'react';
import type { ClassInfo, DeviceConfig, SchoolDeviceInfo, StudentProfileDetail, UserInfoEntry } from '../../api';
import type { DetailTab } from '../../features/device-detail/types';
import type { ImportJob, ImportPreview, ImportRow } from '../../features/device-detail/types';

export type DeviceDetailPageViewProps = {
  loading: boolean;
  schoolDevice: SchoolDeviceInfo | null;
  navigate: (path: string) => void;
  localDevice: DeviceConfig | null;
  isOnline: boolean;
  busyAction: string | null;
  handleTestConnection: () => Promise<void>;
  tab: DetailTab;
  setTab: (tab: DetailTab) => void;
  capabilities: Record<string, unknown> | null;
  configSnapshot: Record<string, unknown> | null;
  timeConfigText: string;
  ntpConfigText: string;
  networkConfigText: string;
  setTimeConfigText: (next: string) => void;
  setNtpConfigText: (next: string) => void;
  setNetworkConfigText: (next: string) => void;
  saveConfig: (key: 'time' | 'ntpServers' | 'networkInterfaces', text: string) => Promise<void>;
  users: UserInfoEntry[];
  usersOffset: number;
  usersTotal: number;
  usersLoading: boolean;
  hasMoreUsers: boolean;
  deviceFaceMap: Record<string, string>;
  deviceFaceLoading: Record<string, boolean>;
  openImportWizard: () => Promise<void>;
  loadDeviceFace: (user: UserInfoEntry) => Promise<void>;
  handleSelectUser: (user: UserInfoEntry) => Promise<void>;
  handleRecreateUser: (user: UserInfoEntry) => Promise<void>;
  handleDeleteUser: (employeeNo: string) => Promise<void>;
  loadUsers: (reset?: boolean) => Promise<void>;
  allSchoolDevices: SchoolDeviceInfo[];
  sourceCloneId: string;
  setSourceCloneId: (next: string) => void;
  handleCloneDbToDevice: () => Promise<void>;
  handleCloneDeviceToDevice: () => Promise<void>;
  selectedUser: UserInfoEntry | null;
  selectedStudentDetail: StudentProfileDetail | null;
  detailLoading: boolean;
  isEditingUser: boolean;
  editFirstName: string;
  editLastName: string;
  editFatherName: string;
  editParentPhone: string;
  editClassId: string;
  editGender: 'MALE' | 'FEMALE';
  editFacePreview: string;
  setIsEditingUser: (next: boolean | ((prev: boolean) => boolean)) => void;
  handleSaveUserEdit: () => Promise<void>;
  handleFaceFileChange: (file?: File) => Promise<void>;
  setEditFirstName: (value: string) => void;
  setEditLastName: (value: string) => void;
  setEditFatherName: (value: string) => void;
  setEditParentPhone: (value: string) => void;
  setEditClassId: (value: string) => void;
  setEditGender: (value: 'MALE' | 'FEMALE') => void;
  closeSelectedUserDetail: () => void;
  buildPhotoUrl: (value?: string | null) => string;
  isImportOpen: boolean;
  setIsImportOpen: (next: boolean) => void;
  importLoading: boolean;
  importRows: ImportRow[];
  previewStats: {
    total: number;
    invalid: number;
    done: number;
    failed: number;
    pending: number;
  };
  importPreview: ImportPreview | null;
  importMetrics: {
    totalRuns: number;
    totalSuccess: number;
    totalFailed: number;
    totalSynced: number;
    successRate: number;
    retryRate: number;
    meanLatencyMs: number;
  } | null;
  importSyncMode: 'none' | 'current' | 'all' | 'selected';
  setImportSyncMode: (mode: 'none' | 'current' | 'all' | 'selected') => void;
  importSelectedDeviceIds: string[];
  getImportDeviceStatus: (device: SchoolDeviceInfo) => 'online' | 'offline' | 'no_credentials';
  toggleImportSelectedDevice: (deviceId: string) => void;
  importPullFace: boolean;
  setImportPullFace: (next: boolean) => void;
  availableClasses: ClassInfo[];
  updateImportRow: (index: number, patch: Partial<ImportRow>) => void;
  processImportRows: (targetIndexes?: number[], retryOnly?: boolean) => Promise<void>;
  refreshImportPreview: () => Promise<void>;
  saveImportRows: () => Promise<void>;
  retryFailedImportRows: () => Promise<void>;
  importJob: ImportJob | null;
  importAuditTrail: Array<{ at: string; stage: string; message: string }>;
  pendingDeleteEmployeeNo: string | null;
  setPendingDeleteEmployeeNo: (next: string | null) => void;
  deleteDialogRef: React.RefObject<HTMLDivElement | null>;
  onDeleteDialogKeyDown: React.KeyboardEventHandler<HTMLDivElement>;
  confirmDeleteUser: () => Promise<void>;
};
